AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 to DynamoDB Logger - Fixed Circular Dependency

Resources:
  ImageMetadataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-upload-bucket"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, PUT, POST, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000
  # Generate Presigned URL for the bucket
  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-logger/
      Handler: get-url.handler
      Runtime: nodejs20.x
      Architectures: [arm64]
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref UploadBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref UploadBucket
      Events:
        UploadApi:
          Type: HttpApi
          Properties:
            Path: /upload
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Format: "cjs"
        EntryPoints:
          - get-url.ts

  ImageEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ImageUploadEvents

  ImageEventsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ImageEventsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref ImageEventsTopic

  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-logger/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref ImageMetadataTable
          TOPIC_ARN: !Ref ImageEventsTopic
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageMetadataTable
        - S3ReadPolicy:
            BucketName: !Sub "${AWS::StackName}-upload-bucket"
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ImageEventsTopic.TopicName
      Events:
        NewFileEvent:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Format: "cjs" # Your current format
        EntryPoints:
          - app.ts

  ImageAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-logger/
      Handler: image-analyzer.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref ImageMetadataTable
      Events:
        TopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref ImageEventsTopic
      Policies:
        - RekognitionDetectOnlyPolicy: {}
        - S3ReadPolicy:
            BucketName: !Ref UploadBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageMetadataTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Format: "cjs"
        EntryPoints:
          - image-analyzer.ts

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  BucketName:
    Description: "Upload bucket name"
    Value: !Ref UploadBucket
  TableName:
    Value: !Ref ImageMetadataTable