AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Media Processor - AI-Powered Image Tagger

Resources:

  AuthCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-user-pool"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  AuthCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref AuthCognitoUserPool
      ClientName: !Sub "${AWS::StackName}-user-pool-client"
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  MediaProcessorApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "${AWS::StackName}-image-api"
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - POST
          - GET
          - OPTIONS 
        AllowHeaders:
          - Authorization
          - Content-Type
        MaxAge: 3000
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              Issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${AuthCognitoUserPool}"
              Audience:
                - !Ref AuthCognitoUserPoolClient
        DefaultAuthorizer: MyCognitoAuthorizer

  ImageMetadataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-upload-bucket"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, PUT, POST, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000

  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-logger/
      Handler: get-url.handler
      Runtime: nodejs20.x
      Architectures: [arm64]
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref UploadBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref UploadBucket
      Events:
        UploadApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref MediaProcessorApi
            Path: /upload
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Format: "cjs"
        EntryPoints:
          - get-url.ts

  ImageEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ImageUploadEvents

  ImageEventsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ImageEventsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref ImageEventsTopic

  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-logger/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref ImageMetadataTable
          TOPIC_ARN: !Ref ImageEventsTopic
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageMetadataTable
        - S3ReadPolicy:
            BucketName: !Sub "${AWS::StackName}-upload-bucket"
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ImageEventsTopic.TopicName
      Events:
        NewFileEvent:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Format: "cjs"
        EntryPoints:
          - app.ts

  ImageAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-logger/
      Handler: image-analyzer.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref ImageMetadataTable
      Events:
        TopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref ImageEventsTopic
      Policies:
        - RekognitionDetectOnlyPolicy: {}
        - S3ReadPolicy:
            BucketName: !Ref UploadBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageMetadataTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Format: "cjs"
        EntryPoints:
          - image-analyzer.ts

Outputs:
  ApiUrl:
    Description: "API Gateway HTTP API endpoint URL"
    Value: !Sub "https://${MediaProcessorApi}.execute-api.${AWS::Region}.amazonaws.com"
  BucketName:
    Description: "Upload bucket name"
    Value: !Ref UploadBucket
  TableName:
    Description: "DynamoDB table name"
    Value: !Ref ImageMetadataTable
  UserPoolId:
    Description: "Cognito User Pool ID for authentication"
    Value: !Ref AuthCognitoUserPool
  UserPoolClientId:
    Description: "Cognito User Pool App Client ID"
    Value: !Ref AuthCognitoUserPoolClient
  UserPoolIssuerUrl:
    Description: "Cognito User Pool Issuer URL for JWT validation"
    Value: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${AuthCognitoUserPool}"