AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 to DynamoDB Logger - Fixed Circular Dependency

Resources:
  ImageMetadataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-upload-bucket"

  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-logger/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref ImageMetadataTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageMetadataTable
        - RekognitionDetectOnlyPolicy: {}
        - S3ReadPolicy:
            BucketName: !Sub "${AWS::StackName}-upload-bucket"
      Events:
        NewFileEvent:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Format: "cjs" # Your current format
        EntryPoints:
          - app.ts

Outputs:
  BucketName:
    Value: !Ref UploadBucket
  TableName:
    Value: !Ref ImageMetadataTable