AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 to DynamoDB Logger (Simple Version)

Resources:
  # 1. DynamoDB Table to store image metadata
  ImageMetadataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  # 2. S3 Bucket for image uploads
  UploadBucket:
    Type: AWS::S3::Bucket

  # 3. The Lambda Function
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-logger/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 20
      Environment:
        Variables:
          TABLE_NAME: !Ref ImageMetadataTable
      Policies:
        # Grants CRUD permissions specifically to our new table
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageMetadataTable
      Events:
        # Trigger on ANY file creation in the bucket
        NewFileEvent:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

    Metadata:
      # Tells SAM how to compile your TypeScript app.ts
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Format: "cjs"
        EntryPoints:
          - app.ts

Outputs:
  BucketName:
    Description: "Upload images here"
    Value: !Ref UploadBucket
  TableName:
    Description: "Metadata will appear here"
    Value: !Ref ImageMetadataTable